### ISSUE TITLE
incorrect indication of delivery status

### ISSUE THREAD

**Issue by martinpecho** [Nuncio-j-s-a/doMail#2]
After viewing the communication detail and then clicking on communications in the menu, the delivery status is marked as unknown even though the message was delivered. The icon should be green, but it is yellow.

1. communication detail

![image](https://github.com/Nuncio-j-s-a/doMail/assets/32236592/df7c7298-e147-49d1-b507-620c6fb61dc7)

2. communication list

![Screenshot 2024-07-10 095841 (1)](https://github.com/Nuncio-j-s-a/doMail/assets/32236592/ce9c9410-9ab0-4834-9715-46290fcc3b44)

**Comment by Nuncio-j-s-a** [comment]
fixed in version 1.0.1.
